name: Build and Release Passcraft

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release

  release:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/upload-release@v1
        with:
          name: passcraft
          path: target/release/passcraft
